spring:
  mail:
    port: 587
    default-encoding: utf-8
    host: smtp.qq.com
    username: 2385290553@qq.com
    password: jwshbsnjxdzyebbf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youthpath?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 11223344
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  session:
    timeout: 1800  # 30分钟
    cookie:
      same-site: lax  # 本地开发使用lax，跨域时none需要secure=true，但本地http用lax
      secure: false   # 本地开发通常为HTTP，设置为false
      http-only: true
      path: /api
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.web.entity.**
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 30m
      cookie:
        same-site: lax
        secure: false
        http-only: true
        max-age: 1800
        path: /api
rsa:
  private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIyAH1tFskobZpzEsLVLq8JjSRNdlBYAPhUR3IYb1pLRbTPpP+DT38biUp/I9EY07UidPSqqmHxfStjfyysqPQCF24cVOzapBKoC+pnL+qn/y24SJdhCAZdpSFVPRwxQGlvmMKR/z7IGWJNfxEmB9SxYBtJgcg7KStsoj/8APTebAgMBAAECgYALnGr69/+L8EfCnN6dnOtM3Tekyg764no+84Lt8k8BQx1rNNN6mQfdP8bkPY8yXh1d6uCrLf38CUP+OEBqCMuRp7mOt/lCWiq5ULbExuxxaWe0/0YeFDgzia/Gp/OJwvj+fpjAECBWu4RhTEVPB7+BQJGSn/bx703Y3EuW35UbQQJBAKD7N6tQg2r005oSDb7JKtzZ7KUFD7Hts2EN6cHuecY+DI62KDX78dFF9xcG+iOKef2Ui5TzMtIzGb9y05IgL0cCQQDfbi+T5ClwHUkzljs9KMiY3qyVEEU89+uBdEJZDyHsbLCK8OgEOwliTV9ffmIJZ5/SLtEe/XIsSUiu2/rg4ScNAkArhN5+1KxCXN9bdmf63L1WqR89WUnt6vmkUjOQdty6yAlzBzGFro+n6Ics1XkH5Kan8+FsKfbiNmhOhkdF6Kd/AkEAgTMNLh7s21kEAGGqJcaUoNl6wMPk1cmjFHuu9iLrAfUj7WQ7Nl8RIRgOw4Conjme0IKkCKCUSgmijwLDwxBPbQJAe6MXFR5uPDQapoSclhrUlM+irvXUFciqdosnIrrb6Ng4rGG4vY3xFWAI8n43iQ53Yz7/3RiK1XXr3P6t11mHWA==
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCMgB9bRbJKG2acxLC1S6vCY0kTXZQWAD4VEdyGG9aS0W0z6T/g09/G4lKfyPRGNO1InT0qqph8X0rY38srKj0AhduHFTs2qQSqAvqZy/qp/8tuEiXYQgGXaUhVT0cMUBpb5jCkf8+yBliTX8RJgfUsWAbSYHIOykrbKI//AD03mwIDAQAB
# 数据库存储专用固定 AES 密钥（永久不改）
aes-storage:
  key: 8KmNcQa7sV2fG9pX
  iv: 5ZrBvEa4sDfGhJkL
